### ISSUE TITLE
Repology information always shows the latest version

### ISSUE THREAD

**Issue by DismissedGuy** [pacstall/website#228]
(partially copied from discord)

There is an issue with how the website gets repology information - it appears to get the latest available version of a package, but this introduces issues when a non-linux package under the same repology project has a higher version number.

For example, `discord-canary`'s latest version according to the website is 0.0.316, but this is for the windows version - the actual latest version for linux is 0.0.146, but the repology project (https://repology.org/project/discord-canary/versions) has the version set to the former because it includes the Scoop repo

This also introduces issues with pacbot, which appears to now be making unresolvable issues such as https://github.com/pacstall/pacstall-programs/issues/2062

A fix for this would be to use the most common version instead, which is how Pacup handles it: https://github.com/pacstall/pacup/blob/e24c91e432eecd29e6ca8a5ab299bcbeff3aecb0/pacup/version.py#L178

**Comment by DismissedGuy** [comment]
Any update on this? Pacbot keeps creating issues...

**Comment by dxbednarczyk** [comment]
AUR has historically been up to date for this package, might be better to use its version as latest rather than the most common version, since as of 2/12/2023 most repos are still out-of-date

**Comment by DismissedGuy** [comment]
I use pacup to keep `discord-canary` up to date, and surprisingly it's pretty accurate. The only times when it isn't is when no other repo has the new version yet. So I'm suspecting there's a bit more going on than simply picking the latest version. In any case, I think that method works quite well and is better than relying on a single other repository.

**Comment by Henryws** [comment]
`pacup` is accurate because it uses a different method for getting the latest version. It gets the average of all the available versions, meaning that if, lets say one repo has some package with a version `3.0.0` because they formatted it differently or something, but everyone else has `2.0.0`, pacup will select `2.0.0`.

We're going to fix this issue on the website API as @saenai255 is trying to rewrite it in rust (🚀)

**Comment by wizard-28** [comment]
@DismissedGuy You can add the [`repo` filter](https://github.com/pacstall/pacup/wiki/Wiki#repo-filter) as a temporary fix.

**Comment by DismissedGuy** [comment]
This still appears to be broken right now: https://github.com/pacstall/pacstall-programs/issues/4663
