### ISSUE TITLE
Add Bengali and Hindi fonts

### ISSUE THREAD

**Issue by Elsie19** [pacstall/website#397]
Currently it seems that the website will try to go back to English when trying to select Bengali as the language.

**Comment by wizard-28** [comment]
Look into adding these fonts specifically:
- [Noto Sans Bengali](https://fonts.google.com/noto/specimen/Noto+Sans+Bengali) for Bengali.
- [Noto Sans Devanagari](https://fonts.google.com/noto/specimen/Noto+Sans+Devanagari) for Hindi.

**Comment by Henryws** [comment]
[`f170b6f` (#443)](https://github.com/pacstall/website/pull/443/commits/f170b6f23d8656514486dce449330e4e21191df3)
