### ISSUE TITLE
Optdepends being split weirdly

### ISSUE THREAD

**Issue by Mar0xy** [pacstall/website#55]
I have noticed that the optional dependencies somehow split per space so if you have extra info in them like
(depend name): (extra info)
this happens
so an-anime-game-launcher-bin has the number of 36 packages even though it's only 12
![image](https://user-images.githubusercontent.com/8841466/160847118-94be6943-6985-4e5a-933e-848579dc1e12.png)

**Comment by D-Brox** [comment]
It should be split at `: `, with the space

**Comment by saenai255** [comment]
A fix for this already exists on a separate development branch. I'll add the fix in the next release, which hopefully will be this week

**Comment by saenai255** [comment]
Fixed in version `2.1.0`
