### ISSUE TITLE
Icon on the Package page

### ISSUE THREAD

**Issue by Mar0xy** [pacstall/website#58]
I have noticed that there is an gear icon on the Package page but I see no real reason behind it.

It could be a possiblity to allow pacscripts to set a custom icon for it through a special variable which the site would display there otherwise I think it would be best to just remove it as no other package overview page from other sites(debian, ubuntu, aur/arch) show an icon aswell.

**Comment by saenai255** [comment]
Yep, it is basically a placeholder for a future release. Hiding it sounds reasonable.

**Comment by Mar0xy** [comment]
> Yep, it is basically a placeholder for a future release. Hiding it sounds reasonable.

Alrighty sounds good. Also on another topic I have realized that the 404 error page doesn't actually get properly used as it redirects to not-found which cause you to get into a loop when you try to go back to the previous functional page "<Navigate to="/not-found" />" but instead like for the not-found page "<NotFound />"

**Comment by saenai255** [comment]
I didn't think of that. Nice.
Btw here's a preview of [an-anime-game-launcher-bin](https://pacstall-website-laxch.ondigitalocean.app/packages/an-anime-game-launcher-bin)
Ideas and suggestions are welcome

**Comment by Mar0xy** [comment]
Yeah, that looks much better compared to the previous mess :laughing:

**Comment by Mar0xy** [comment]
Though it would be nice to know how the sorting works as previous it went by package list order it seemed like but now it's all just jumbled. also why do pages start at 0 instead of 1 as normally you start on 1 and count up

**Comment by saenai255** [comment]
> why do pages start at 0 instead of 1 as normally you start on 1 and count up 

Pages starting from `0` is mostly a joke, as array indexing starts from 0.

> it would be nice to know how the sorting works

The server reads package names from `packagelist` which is already sorted, and then parses them in batches, so currently it is a kind of pseudo-alphabetical sort.
We have planned a sort of popularity/downloads/votes algorithm for page ranking but until then, sure, I can sort them

> you also don't have an fail check implemented yet preventing people from entering non-existent pages in the url.

I'm not sure what you mean by this

**Comment by Mar0xy** [comment]
> I'm not sure what you mean by this

You can basically just replace the number at the end of the url with any number without it erroring.

**Comment by saenai255** [comment]
Improvement released in version `2.1.0`
